### ISSUE TITLE
Resubscribing throwing error

### ISSUE THREAD

**Issue by arashb31** [postaljs/postal.js#152]
I'm using postal.js and sometimes when I subscribe to a channel, I receive an error that looks like this:

For example, if I do something like

` postal.channel().subscribe('newsfeed', alert)
`
I get

`"Cannot read property '/|homefeed' of undefined"
`

Stack trace below:
`    at http://localhost:8080/libs/postal.js:8:730
    at http://localhost:8080/libs/postal.js:8:7297
    at u (http://localhost:8080/libs/lodash.min.js:6:412)
    at Function.se (http://localhost:8080/libs/lodash.min.js:52:212)
    at Object.e.extend.subscribe (http://localhost:8080/libs/postal.js:8:7187)
    at p.subscribe (http://localhost:8080/libs/postal.js:8:1471)
`

**Comment by ifandelse** [comment]
@arashb31 I apologize for the delay in responding. I've not been able to reproduce the issue. Do you have a gist, jsfiddle or something that consistently shows this happening? Also - what version of postal and lodash were you using?
